// <auto-generated />
namespace Project_PBO.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class InisialisasiAwal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InisialisasiAwal));
        
        string IMigrationMetadata.Id
        {
            get { return "202512110158166_InisialisasiAwal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
